name: Actualizar Kit Frio

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pipeline
        env:
          KEY_OP_FRIO: ${{ secrets.KEY_OP_FRIO }}
          URL_OP_FRIO: ${{ secrets.URL_OP_FRIO }}
          URL_CASOS_CRITICOS: ${{ secrets.URL_CASOS_CRITICOS }}
        run: |
          python pipeline.py
          python exporter.py

      - name: Commit cambios
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git diff --cached --quiet || git commit -m "auto update"

      - name: Push
        run: git push
